import { describe, it } from "node:test";
import assert from "node:assert";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { collectTier1Links, writeGraphLinks } from "../lib/obsidian/graph-link-writer.js";
import { backfillMemoryNoteScope, writeMemoryNotes } from "../lib/obsidian/memory-note-writer.js";

function makeVault(prefix) {
  return mkdtempSync(join(tmpdir(), prefix));
}

function memoryRecord(id, overrides = {}) {
  return {
    id,
    text: `Memory ${id}`,
    summary: `Summary ${id}`,
    category: "fact",
    importance: 0.8,
    createdAt: "2026-06-01T00:00:00.000Z",
    scope: "workspace",
    status: "active",
    ...overrides,
  };
}

describe("graph link memory target resolution", () => {
  it("resolves explicit memoryIds through byMemoryId before byId", () => {
    const links = collectTier1Links({
      memoryIds: ["mem-1"],
      sourceRefs: [],
    }, {
      byId: {
        "mem-1": {
          plur1bus_id: "mem-1",
          plur1bus_type: "decision",
          path: "records/decision/mem-1.md",
          title: "Decision With Same Id",
        },
      },
      byMemoryId: {
        "mem-1": {
          memory_id: "mem-1",
          plur1bus_type: "memory",
          path: "memories/mem-1.md",
          title: "Mirror Memory",
        },
      },
    }, "plur1bus", 5);

    assert.deepStrictEqual(links, [
      "- [[plur1bus/memories/mem-1|Mirror Memory]] _(memoryId)_",
    ]);
  });

  it("does not prefer generated byId records over real memory mirror targets", () => {
    const links = collectTier1Links({
      memoryIds: ["mem-2"],
    }, {
      byId: {
        "mem-2": {
          plur1bus_id: "mem-2",
          plur1bus_type: "duplicate_candidate",
          path: "records/duplicate_candidate/mem-2.md",
          title: "Generated Duplicate",
        },
      },
      byMemoryId: {
        "mem-2": {
          memory_id: "mem-2",
          plur1bus_type: "memory",
          path: "memories/mem-2.md",
          title: "Real Memory",
        },
      },
    }, "plur1bus", 5);

    assert.deepStrictEqual(links, [
      "- [[plur1bus/memories/mem-2|Real Memory]] _(memoryId)_",
    ]);
  });

  it("resolves sourceRefs by byId first and falls back to byMemoryId", () => {
    const links = collectTier1Links({
      sourceRefs: ["source-1", "mem-3"],
    }, {
      byId: {
        "source-1": {
          plur1bus_id: "source-1",
          plur1bus_type: "decision",
          path: "records/decision/source-1.md",
          title: "Source Decision",
        },
      },
      byMemoryId: {
        "mem-3": {
          memory_id: "mem-3",
          plur1bus_type: "memory",
          path: "memories/mem-3.md",
          title: "Fallback Memory",
        },
      },
    }, "plur1bus", 5);

    assert.deepStrictEqual(links, [
      "- [[plur1bus/records/decision/source-1|Source Decision]] _(Quelle)_",
      "- [[plur1bus/memories/mem-3|Fallback Memory]] _(Quelle)_",
    ]);
  });

  it("resolves source_memories as memory targets through byMemoryId", () => {
    const links = collectTier1Links({
      source_memories: ["mem-4"],
    }, {
      byId: {},
      byMemoryId: {
        "mem-4": {
          memory_id: "mem-4",
          plur1bus_type: "memory",
          path: "memories/mem-4.md",
          title: "Knowledge Source Memory",
        },
      },
    }, "plur1bus", 5);

    assert.deepStrictEqual(links, [
      "- [[plur1bus/memories/mem-4|Knowledge Source Memory]] _(source_memory)_",
    ]);
  });

  it("does not write broken links for missing source_memories", () => {
    const links = collectTier1Links({
      source_memories: ["missing-memory"],
    }, {
      byId: {},
      byMemoryId: {},
    }, "plur1bus", 5);

    assert.deepStrictEqual(links, []);
  });

  it("does not use generated records as source_memories link targets", () => {
    const links = collectTier1Links({
      source_memories: ["generated-memory"],
    }, {
      byId: {},
      byMemoryId: {
        "generated-memory": {
          memory_id: "generated-memory",
          plur1bus_type: "provenance",
          path: "records/provenance/generated-memory.md",
          title: "Generated Provenance",
        },
      },
    }, "plur1bus", 5);

    assert.deepStrictEqual(links, []);
  });

  it("does not create empty graph blocks when no links are available", async () => {
    const vault = makeVault("graph-no-empty-");
    const noteDir = join(vault, "plur1bus", "notes");
    mkdirSync(noteDir, { recursive: true });
    const notePath = join(noteDir, "empty.md");
    writeFileSync(notePath, "---\nplur1bus_id: empty\nplur1bus_type: knowledge\n---\n\n# Empty\n", "utf8");

    const result = await writeGraphLinks({
      vaultPath: vault,
      reviewRoot: "plur1bus",
      graphLinks: { tiers: ["explicit"], maxPerNote: 5 },
    }, [{
      plur1bus_id: "empty",
      plur1bus_type: "knowledge",
      path: "notes/empty.md",
      memoryIds: ["missing"],
    }]);

    const content = readFileSync(notePath, "utf8");
    assert.strictEqual(result.updated, 0);
    assert.strictEqual(result.unchanged, 1);
    assert.doesNotMatch(content, /plur1bus:managed:start/);
  });

  it("does not create empty graph blocks when semantic tier has no index links", async () => {
    const vault = makeVault("graph-semantic-no-empty-");
    const noteDir = join(vault, "plur1bus", "memories");
    mkdirSync(noteDir, { recursive: true });
    const notePath = join(noteDir, "mem-a.md");
    writeFileSync(notePath, [
      "---",
      "memory_id: mem-a",
      "plur1bus_type: memory",
      "agent_id: main",
      "workspace_id: main",
      "---",
      "",
      "# Memory A",
      "",
      "Body",
    ].join("\n"), "utf8");

    const result = await writeGraphLinks({
      vaultPath: vault,
      reviewRoot: "plur1bus",
      graphLinks: { tiers: ["semantic"], includeSemantic: true, maxPerNote: 5 },
    }, [{
      memory_id: "mem-a",
      plur1bus_type: "memory",
      path: "memories/mem-a.md",
      title: "Memory A",
    }], { linkIndex: { version: "1", entries: {} } });

    const content = readFileSync(notePath, "utf8");
    assert.strictEqual(result.updated, 0);
    assert.strictEqual(result.unchanged, 1);
    assert.doesNotMatch(content, /plur1bus:managed:start/);
  });
});

describe("memory note workspace metadata", () => {
  it("writes stable agent_id and workspace_id when supplied by workspace config", () => {
    const vault = makeVault("memory-scope-meta-");
    const id = "aaaaaaaa-2222-4222-8222-aaaaaaaaaaa1";

    writeMemoryNotes({
      vaultPath: vault,
      reviewRoot: "plur1bus",
      agentId: "bernhardine",
      workspaceKey: "bernhardine",
    }, [memoryRecord(id)], { maxPerRun: 1 });

    const content = readFileSync(join(vault, "plur1bus", "memories", `${id}.md`), "utf8");
    assert.match(content, /^agent_id: bernhardine$/m);
    assert.match(content, /^workspace_id: bernhardine$/m);
  });

  it("does not invent tags topics or reference arrays for memory mirrors", () => {
    const vault = makeVault("memory-no-invented-meta-");
    const id = "bbbbbbbb-2222-4222-8222-bbbbbbbbbbb1";

    writeMemoryNotes({
      vaultPath: vault,
      reviewRoot: "plur1bus",
      agentId: "main",
      workspaceKey: "main",
    }, [memoryRecord(id)], { maxPerRun: 1 });

    const content = readFileSync(join(vault, "plur1bus", "memories", `${id}.md`), "utf8");
    assert.doesNotMatch(content, /^tags:/m);
    assert.doesNotMatch(content, /^topics:/m);
    assert.doesNotMatch(content, /^sourceRefs:/m);
    assert.doesNotMatch(content, /^memoryIds:/m);
  });

  it("stays idempotent when writing the same scoped memory twice", () => {
    const vault = makeVault("memory-scope-idem-");
    const id = "cccccccc-2222-4222-8222-ccccccccccc1";
    const config = {
      vaultPath: vault,
      reviewRoot: "plur1bus",
      agentId: "heisenberg",
      workspaceKey: "heisenberg",
    };

    writeMemoryNotes(config, [memoryRecord(id)], { maxPerRun: 1 });
    const filePath = join(vault, "plur1bus", "memories", `${id}.md`);
    assert.ok(existsSync(filePath));
    const before = statSync(filePath).mtimeMs;
    const result = writeMemoryNotes(config, [memoryRecord(id)], { maxPerRun: 1 });
    const after = statSync(filePath).mtimeMs;

    assert.strictEqual(result.written, 0);
    assert.strictEqual(result.skipped, 1);
    assert.strictEqual(after, before);
  });

  it("backfills only agent_id and workspace_id on existing memory mirrors without changing body", () => {
    const vault = makeVault("memory-scope-backfill-");
    const dir = join(vault, "plur1bus", "memories");
    mkdirSync(dir, { recursive: true });
    const filePath = join(dir, "dddddddd-2222-4222-8222-ddddddddddd1.md");
    const body = "# Existing\n\nBody stays byte-for-byte.\n";
    const beforeContent = [
      "---",
      "memory_id: dddddddd-2222-4222-8222-ddddddddddd1",
      "plur1bus_type: memory",
      "category: fact",
      "content_hash: sha256:test",
      "---",
      "",
      body,
    ].join("\n");
    writeFileSync(filePath, beforeContent, "utf8");
    const beforeBody = beforeContent.slice(beforeContent.indexOf("---\n", 4) + 5);

    const result = backfillMemoryNoteScope({
      vaultPath: vault,
      reviewRoot: "plur1bus",
      agentId: "main",
      workspaceKey: "main",
    });
    const content = readFileSync(filePath, "utf8");
    const afterBody = content.slice(content.indexOf("---\n", 4) + 5);

    assert.strictEqual(result.updated, 1);
    assert.strictEqual(result.skipped, 0);
    assert.match(content, /^agent_id: main$/m);
    assert.match(content, /^workspace_id: main$/m);
    assert.doesNotMatch(content, /^tags:/m);
    assert.doesNotMatch(content, /^topics:/m);
    assert.doesNotMatch(content, /^sourceRefs:/m);
    assert.doesNotMatch(content, /^memoryIds:/m);
    assert.strictEqual(afterBody, beforeBody);
  });

  it("scope backfill is idempotent on a second run", () => {
    const vault = makeVault("memory-scope-backfill-idem-");
    const dir = join(vault, "plur1bus", "memories");
    mkdirSync(dir, { recursive: true });
    const filePath = join(dir, "eeeeeeee-2222-4222-8222-eeeeeeeeeee1.md");
    writeFileSync(filePath, [
      "---",
      "memory_id: eeeeeeee-2222-4222-8222-eeeeeeeeeee1",
      "plur1bus_type: memory",
      "agent_id: heisenberg",
      "workspace_id: heisenberg",
      "content_hash: sha256:test",
      "---",
      "",
      "# Existing",
      "",
    ].join("\n"), "utf8");

    const first = backfillMemoryNoteScope({
      vaultPath: vault,
      reviewRoot: "plur1bus",
      agentId: "heisenberg",
      workspaceKey: "heisenberg",
    });
    const before = statSync(filePath).mtimeMs;
    const second = backfillMemoryNoteScope({
      vaultPath: vault,
      reviewRoot: "plur1bus",
      agentId: "heisenberg",
      workspaceKey: "heisenberg",
    });
    const after = statSync(filePath).mtimeMs;

    assert.strictEqual(first.updated, 0);
    assert.strictEqual(first.skipped, 1);
    assert.strictEqual(second.updated, 0);
    assert.strictEqual(second.skipped, 1);
    assert.strictEqual(after, before);
  });
});
